spring.application.name=bookstore
#spring.profiles.active=local-postgre
spring.jpa.show-sql=true
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb

# Jos haluaisi käyttää Spring Data RESTiä
# spring.data.rest.base-path=/api

# Local Database, ei käytössä
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
spring.datasource.username=postgres
spring.datasource.password=SQL1SiotonKalasana3

# JPA/hibernate ei tee muutoksia ulkoiseen kantaan
#spring.jpa.hibernate.ddl-auto=none