spring.application.name=musiikkikokoelma
spring.jpa.show-sql=true

# Terminaali logi
logging.level.org.springframework.web=TRACE

# H2-tietokanta (Rahti)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb

# PostgreSQL-tietokanta
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=jdbc:postgresql://localhost:5432/musiikkikokoelma
#spring.datasource.username=postgres
#spring.datasource.password=salasana